services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: timescale_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
